print("Getting to know you!")
print()
myName = input("Whats's your name?:")
myFood = input("What's your favourite food?:")
myMusic = input("What's your favourite music?:")
myCity = input("Where do you live?:")
print()
print("Hi,")
print(myName)
print("So you're telling me that your favourite food is")
print(myFood)
print("and that you listen to")
print(myMusic)
print("and that you live in")
print(myCity)
answer = input("is that right?:")
print("Well that's fantastic!")